# Generated by Django 4.2.5 on 2023-09-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_server', '0004_remove_user_registration_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
