# Generated by Django 4.2.5 on 2023-09-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws_server', '0003_user_registration_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_method',
        ),
    ]
